### ISSUE TITLE
iPhone 6 + iOS 9.3.1 + Safari 9: Transparent materials look white from far/medium distance

### ISSUE THREAD

**Issue by micsun-al** [playcanvas/webvr#3] opened 2016-04-21 03:50 UTC
Before VR:
![image](https://cloud.githubusercontent.com/assets/15949921/14697455/e37a4fee-0738-11e6-87df-f5ad9dc67b16.png)

After VR initializes on touch event, the bush and the tree branches turn white:
![image](https://cloud.githubusercontent.com/assets/15949921/14697465/ecf85340-0738-11e6-9ea2-db8b45c218c5.png)

Up close, the transparent things seem to look ok:
![image](https://cloud.githubusercontent.com/assets/15949921/14697482/fd0ac92a-0738-11e6-9ecc-b62836685291.png)

I can share out my project if you want to take a closer look (it's private)?

Thank you!

**Comment by daredevildave** [comment] 2016-04-21 06:59
Looks to me like an engine bug rather than something specific to this library. I've raised an issue in the engine: https://github.com/playcanvas/engine/issues/573

**Comment by willeastcott** [comment] 2016-04-21 08:12
Certainly, a simple reproducible case would be a big help. But can I ask a couple of questions:
- Does this effect happen if fog is disabled?
- Do you have any post effects enabled? If so, does this problem happen if you disable them?

**Comment by micsun-al** [comment] 2016-04-21 19:06
Oops, I just got this to reproduce before the vrCamera engages, so I guess not related to WebVR.
![image](https://cloud.githubusercontent.com/assets/15949921/14721044/28864efa-07b9-11e6-90c8-8476f3729616.png)

Disabling fog makes the bush display correctly.
![image](https://cloud.githubusercontent.com/assets/15949921/14719713/a21e7fd2-07b2-11e6-88b5-2824a6c4945c.png)

Post effects enabled, but reproduces with them disabled: bloom, brighnesscontrast, fxaa, huesaturation, sepia, vignette

I think this might be related to the particle system (I have large fog-like particles spawning in a large area around the player), but kind of shooting in the dark here.

Thank you!

**Comment by Maksims** [comment] 2017-02-24 16:02
@micsun-al is this still a problem, could you please give us a link to demo that replicates an issue and potentially project it self?

**Comment by willeastcott** [comment] 2022-02-02 23:14
Closing because the [core engine now supports WebXR](https://developer.playcanvas.com/en/user-manual/xr/) and WebVR has been discontinued.

**Closed as completed by willeastcott** 2022-02-02 23:14 UTC
